export const FORM_STEP_CHANGE = 'FORM_STEP_CHANGE';
export const FIREWALL_SETTING_CHANGE = 'FIREWALL_SETTING_CHANGE';
export const PROTECTION_SELECTED_FEATURE = 'PROTECTION_SELECTED_FEATURE';
export const SET_ENABLED_FEATURES = 'SET_ENABLED_FEATURES';
export const SET_DISABLED_FEATURES = 'SET_DISABLED_FEATURES';
