export const FORM_STEP_CHANGE = 'FORM_STEP_CHANGE';
export const FIREWALL_CHANGE = 'FIREWALL_CHANGE';
export const PROTECTION_SELECTED_FEATURE = 'PROTECTION_SELECTED_FEATURE';
export const SET_ENABLED_FEATURES = 'SET_ENABLED_FEATURES';
export const SET_DISABLED_FEATURES = 'SET_DISABLED_FEATURES';
export const SET_SYSTEM_STATUS = 'SET_SYSTEM_STATUS';
export const SET_FILES_SCANNED = 'SET_FILES_SCANNED';
export const SET_THREATS_COUNT = 'SET_THREATS_COUNT';
